name: ticket_support_system
description: "A ticket support system built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  mailer: ^6.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  faker: ^2.0.0
  mongo_dart: ^0.10.3
  equatable: ^2.0.3

dependency_overrides:
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Web configurations
  web:
    build:
      defaults:
        options:
          renderer: canvaskit
          optimize: true
